[profile.default]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
    "../../node_modules",
]
evm_version = "paris"
remappings = [
    "@arbitrum/=../../node_modules/@arbitrum/",
    "@chainlink/=../../node_modules/@chainlink/",
    "@eth-optimism/=../../node_modules/@chainlink/contracts/node_modules/@eth-optimism/",
    "@offchainlabs/=../../node_modules/@offchainlabs/",
    "@openzeppelin/=../../node_modules/@openzeppelin/",
    "@scroll-tech/=../../node_modules/@scroll-tech/",
    "@zksync/=../../node_modules/@zksync/",
    "eth-gas-reporter/=../../node_modules/eth-gas-reporter/",
    "hardhat/=../../node_modules/hardhat/",
    "solady/=../../node_modules/solady/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
